### PR TITLE
[charts/redis-ha] Readonly filesystem and Probes

### PR DESCRIPTION
**Pull request by sindrip**
#### What this PR does / why we need it:

This adds a `securityContext` on each container with a configuration option for `readOnlyRootFilesystem` defaulted to false.

This also adds readiness and liveness probes for the split-brain-fix container. The probes are defaulted to off.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@sindrip Sorry, I wasn't notified via email about this :( I'll check and test over the coming next couple of days.

**Comment by sindrip** [comment]
Hi, don't worry about it, I just assumed you were busy with other things. Thank you!

**Comment by haljin** [comment]
Hi, any progress on this? We could use that change as well

**Comment by sindrip** [comment]
I saw that some conflicts had been introduced from a merge that I have resolved now.

@DandyDeveloper do you have time to look at this?

**Comment by DandyDeveloper** [comment]
@sindrip I do, I will be checking shortly. I can't believe this has been open so long, sorry.

**Comment by sindrip** [comment]
Hi @DandyDeveloper, no worries. Is there anything you want me to do to enable this, or are you planning to take care of these new conflicts?

**Comment by DandyDeveloper** [comment]
@sindrip I know this is ancient, but I don't want to close it if you think it's still helpful. 

Can you just revise this for me and let me know if you're still happy with how this looks?

**Comment by sindrip** [comment]
I don't need it anymore, closing.

**Pull request closed without merging**
