### PR TITLE
[stable/redis-ha] Opt in/out of automounting API credentials into container (autautomountServiceAccountToken)

### PR DESCRIPTION
**Pull request by ebgc**
#### What this PR does / why we need it:

Opt in/out of automounting API credentials into container

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@ebgc Can you make sure you @ me for these PRs, I don't have autoreviews setup yet, sorry. 

Can you explain the justification / need for this? I get the function, but is this something you need?

**Comment by ebgc** [comment]
> @ebgc Can you make sure you @ me for these PRs, I don't have autoreviews setup yet, sorry.
> 
> Can you explain the justification / need for this? I get the function, but is this something you need?

the reason for this PR is:
* to be able to continue using the public available redis-ha helm chart without always needing to merge in our changes
* to have it visible that the pod created from that chart has no kubectl api access to k8s api (one could use rbac rules here - but thats an overhead which one can short-cut while preventing k8s-api direct from pod)

@DandyDeveloper

**Comment by DandyDeveloper** [comment]
I think this only needs a patch update @ebgc 

Can you get ready for me to merge your other PR and fix the merge? OR can you give me access to your fork? I'll fix the conflicts.

**Comment by ebgc** [comment]
added you to https://github.com/GrabCAD/charts


___
GrabCAD
Enrico B.

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
