### PR TITLE
[stable/redis-ha] Slave priority - never promote defined slave to be master

### PR DESCRIPTION
**Pull request by ebgc**
#### What this PR does / why we need it:

if one needs a redis slave which must stay read-only - use the option ro_replicas to index slaves never promoted to be master

using slave_priority : https://redis.io/topics/sentinel

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@ebgc Again, would be great to get an explanation on use case here. I am trying my best to prevent excessive functions in the chart in an effort to not confuse people. 

I definitely get what is being asked here, I just want to make sure we're doing this with good reason and not "just incase" someone wants it.

**Comment by ebgc** [comment]
> @ebgc Again, would be great to get an explanation on use case here. I am trying my best to prevent excessive functions in the chart in an effort to not confuse people.
> 
> I definitely get what is being asked here, I just want to make sure we're doing this with good reason and not "just incase" someone wants it.

the reason for this PR is:
* to be able to continue using the public available redis-ha helm chart without always needing to merge in our changes
* we use redis as a shared redis token storage between different namespaces (there are consumer namespaces (read-only access to redis) and the provider namespace (read-write access to redis))
- we dont want that redis consumer namespaces will ever access redis master (letting redis client ask for slave is not enough - we dont want that client has a chance to access master - if by mistake or intentional requesting master access)
- we can achieve this while having networkpolicies setup which allow access to certain redis-ha service endpoints - for this to work we have to set for those redis-ha pods the slave-priority set to 0 (never get promoted to master) - now -> the client can have sentinel endpoint with prioritized (see ioredis) redis slaves set and will always try to connect to them
- our setup is 1 master, 1 ha-slave, 2 ro-slaves - the ha-slave is to make sure we have a slave which can take master role in case master has problems (and after replacement is the new ha-slave)

hope you understand :)

@DandyDeveloper

**Comment by DandyDeveloper** [comment]
@ebgc Very sensible, thanks for explaining. I'll try to review ASAP and test this and get it merged. Thank you!

**Comment by DandyDeveloper** [comment]
@ebgc I thought I had asked, but can you update version here? I'm ready to merge this.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by ebgc** [comment]
master is on 4.6.2
PR is on 4.8.0

to which version i should change it ?

___
GrabCAD
Enrico B.

**Comment by DandyDeveloper** [comment]
@ebgc 4.7.0 please.

**Comment by DandyDeveloper** [comment]
@ebgc Looks like you didn't merge / fix conflicts. Can you do that?

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
