### PR TITLE
[stable/redis-ha] ✨ feat: multiple values for redis configs

### PR DESCRIPTION
**Pull request by mhkarimi1383**
#### What this PR does / why we need it:

When we need to have multiple values for some configs (e.g. loadmodule), yaml is not okay with multiple values for the same key.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by DandyDeveloper — COMMENTED** [review]
Can we add some examples to the CI.yaml so it picks up this test case?

**Comment by mhkarimi1383** [comment]
I didn't find that `CI.yaml` file
I should add a new values file into the `ci` directory in the chart?

**Comment by DandyDeveloper** [comment]
@mhkarimi1383 

https://github.com/dandydeveloper/charts/blob/f39ee0e89964e90e781c682d5333f65b75083eaf/.ci/ct-config.yaml#L3

Apparently we just use base values right now, but we could include a specific ci.yaml that can handle all the test cases. I thought we already had this! I was wrong. 

But under the `ci/` folder in the chart, I'd recommend adding something here and then updating the file I've linked. If you have any Qs or think it's not worth the effort, let me know!

**Comment by mhkarimi1383** [comment]
@DandyDeveloper I added a values file for testing, etc.

As my reading that should work without any changes in  https://github.com/dandydeveloper/charts/blob/f39ee0e89964e90e781c682d5333f65b75083eaf/.ci/ct-config.yaml

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
