### PR TITLE
[stable/redis-ha] Parameterizing redis initialDelaySeconds

### PR DESCRIPTION
**Pull request by muratso**
#### What this PR does / why we need it:

This PR parameterizes redis' initialDelaySeconds.
When the Redis cluster has too much data on it and a replica comes down, there's not enough time for that replica to perform the sync with the master node. It ends up restarting endlessly without never coming back. With this, we can set enough time for this bootstrap tasks before the liveness probe restarts abruptly the pod.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@muratso Completely reasonable. LGTM. Can you bump the version?

**Comment by muratso** [comment]
Hey @DandyDeveloper sorry about this. Thanks for reviewing. I had to push once again because my last commits bumping the version were not signed. Could you please check again?

**Comment by DandyDeveloper** [comment]
@muratso :+1: Just waiting for the CI process to finish

**Comment by DandyDeveloper** [comment]
@muratso Ah just checked, can you make sure it's above 4.6.X because I merged something that bumped the minor version.

**Comment by muratso** [comment]
@DandyDeveloper are you sure? In the master branch I still can see it is 4.5.8

**Comment by DandyDeveloper** [comment]
@muratso Oh I didn't merge it... Nevermind, we're good. Merging!

**Comment by muratso** [comment]
Cool! Thanks!

**Pull request merged**
