### PR TITLE
[charts/redis-ha] Pull S3 credentials from k8s secret

### LINKED ISSUE #65: [chart/redis-ha][REQUEST] Pull S3 credentials from k8s secret
**Is your feature request related to a problem? Please describe.**
AWS S3 credentials should be able to be pulled from a Kubernetes secret instead of a string in the values.yaml file.

**Describe the solution you'd like**
Reference a Kubernetes secret containing S3 keys.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by j771**
- Use existingSecret for AWS or SSH keys

Signed-off-by: Justin StGermain <jstgermain@greathorn.com>

#### What this PR does / why we need it:
  - Adds the ability to use the existingSecret for AWS S3 credentials or SSH key

#### Which issue this PR fixes
  - fixes #65 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@j771 Can you rebase this? Somehow this completely slipped under my radar...

**Comment by j771** [comment]
> @j771 Can you rebase this? Somehow this completely slipped under my radar...

This is so old, I will do another PR. Tell me what version you want me to set the chart to and I will do an updated PR.

**Comment by j771** [comment]
Closing this PR in favor of: https://github.com/DandyDeveloper/charts/pull/139

**Comment by j771** [comment]
> @j771 Can you rebase this? Somehow this completely slipped under my radar...

@DandyDeveloper 
I created this: https://github.com/DandyDeveloper/charts/pull/139
I also just created this: https://github.com/DandyDeveloper/charts/pull/141

**Pull request closed without merging**
