### PR TITLE
stable/redis-ha: add endpointAdditionalProperties for redis-ha and haproxy serviceMonitor

### PR DESCRIPTION
**Pull request by trawler**
#### What this PR does / why we need it:
This PR enables setting additional flags for the prometheus-exporter and redis-ha serviceMonitors (see: [EndpointSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint)).
I opted to create an open nested object called `endpointAdditionalProperties` so that it's not necessary to explicitly expose all available endpoint settings.

Usage Example:
```
exporter:
  serviceMonitor:
    enabled: true
    endpointAdditionalProperties:
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: foo
          replacement: bar
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by trawler** [comment]
@DandyDeveloper - can you trigger the tests?

**Comment by trawler** [comment]
tagging also @ssalaues: can you also help in triggering the tests for this PR? Thanks!

**Review by DandyDeveloper — APPROVED** [review]

**Comment by DandyDeveloper** [comment]
Running the tests now :)

**Comment by trawler** [comment]
hmm looks like my commit was not signed. checking.

**Comment by trawler** [comment]
@DandyDeveloper I re-pushed with a signed commit. Sorry for the hassle!

**Pull request merged**
