### PR TITLE
[stable/redis-ha] bug: quote namespace to allow names with only numbers

### PR DESCRIPTION
**Pull request by gimler**
#### What this PR does / why we need it:

To use a namespace with only numbers for example `123` the namespace name must be quoted.

#### Special notes for your reviewer:

This also follow helm best practices
https://helm.sh/docs/chart_best_practices/values/#make-types-clear

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by gimler** [comment]
@DandyDeveloper can you take a look at this change please

**Comment by DandyDeveloper** [comment]
@gimler Can you bump the chart version again? I merged something recently. 

Thank you!

**Comment by gimler** [comment]
@DandyDeveloper done. ready for merge ;)

**Comment by DandyDeveloper** [comment]
@gimler Sorry for the delay, overwhelmed with a number of things. Getting this merged in the hour.

**Pull request merged**
