### PR TITLE
Newer versions of haproxy expect LF on config last line

### PR DESCRIPTION
**Pull request by tahajahangir**
The current chart fails with haproxy 2.3.2 with following error:

```[NOTICE] 001/071757 (1) : haproxy version is 2.3.2-d522db7
[NOTICE] 001/071757 (1) : path to executable is /usr/local/sbin/haproxy
[ALERT] 001/071757 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:82]: Missing LF on last line, file might have been truncated at position 68.
[ALERT] 001/071757 (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT] 001/071757 (1) : Fatal errors found in configuration.
```

This patch fixes the issue

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@tahajahangir Checking this now.

**Comment by DandyDeveloper** [comment]
@tahajahangir Please remember to include chart version bumps as per the templated options.

**Review by DandyDeveloper — CHANGES_REQUESTED** [review]
Looks good, but you need to bump chart patch version and make sure commits are signed.

**Comment by tahajahangir** [comment]
@DandyDeveloper New signed commit (with changed helm-chart version) is pushed

**Comment by DandyDeveloper** [comment]
@tahajahangir Can you pull in the latest changes from master? I fixed the CI / Made some updates. Want to make sure the CI test succeeds

**Comment by DandyDeveloper** [comment]
@tahajahangir I don't think you pulled in all my changes: 

https://github.com/DandyDeveloper/charts/blob/322c7d65158d09e3ed1e977504d3d22266449c2f/charts/redis-ha/Chart.yaml#L18

This should be removed. It's what is breaking the CI from running.

Please re-pull my latest changes.

**Comment by DandyDeveloper** [comment]
@tahajahangir NEvermind, I've managed to merge them in. Waiting for CI.

**Pull request merged**
