### PR TITLE
add loadBalancerSourceRanges option

### PR DESCRIPTION
**Pull request by imcitius**
#### What this PR does / why we need it:
Add ability to define `loadBalancerSourceRanges` option to haproxy service definition, to allow connect to service only from specific CIDR's.

### CODE REVIEW

**Review by DandyDeveloper — DISMISSED** [review]

**Comment by DandyDeveloper** [comment]
@imcitius Looks good, but I need you to bump chart patch version, please.

**Comment by imcitius** [comment]
> @imcitius Looks good, but I need you to bump chart patch version, please.

Sorry did'nt do that. Fixed now.
Thanks.

**Comment by DandyDeveloper** [comment]
@imcitius Needs to be `.10`. Merge with master if you can! 

Thank you!

**Comment by imcitius** [comment]
Hello.
I bumped to x.10, but merging into master on my side leads to a new PR.
I will do it that way, if you want me to.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by DandyDeveloper** [comment]
@imcitius Working through some PRs now, will probably need to resolve a conflict. I'll do it if I have the necessary access. 

Thank you for the PR.

**Pull request merged**
