### PR TITLE
[charts/redis-ha] Add readiness probe to chart

### PR DESCRIPTION
**Pull request by michael-michalski**
Signed-off-by: Michael Michalski <michaelmartinmichalski@gmail.com>

#### What this PR does / why we need it:
Currently the chart supports liveness probes but not readiness probes.
The self hosted Kubernetes of our company dictates that these are set.

#### Special notes for your reviewer:
Is there an interest in creating a dedicated readiness probe or is it good enough to reuse the /health/redis_liveness.sh

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by MaartenFaddegon** [comment]
@DandyDeveloper would also be keen to see this merged, could you have a look?

**Comment by DandyDeveloper** [comment]
On it first thing in my morning. Sorry its my birthday today!

**Comment by MaartenFaddegon** [comment]
Happy birthday! 🎂

**Comment by tahajahangir** [comment]
I've requested a PR on your PR (https://github.com/michael-michalski/charts/pull/1 @michael-michalski ).

With recent changes to `redis_liveness.sh`, the POD (wrongly) will be marked as ready when a sync is in progress.
I've added an new `redis_readiness.sh`.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by tahajahangir** [comment]
I also recommend setting `readiness.successThreshold` to higher values (e.g. `5`), because when redis starts, first readiness checks wrongly reports ready state. But after some time (e.g. 1 minute), sentinel may trigger a resync and changes to an unavailable state.

This may cause total data loss in a rolling update process.

**Pull request merged**
