### PR TITLE
[charts/redis-ha] Add extraAnnotations value allowing to add annotations for every sing…

### PR DESCRIPTION
**Pull request by imvalient**
…le resource generate, from a single value declaration

#### What this PR does / why we need it:
I've been using this chart for a long time. Right now, I'm trying to add a custom annotation to all the resources generated by this chart, but currently, it's not supported. This PR enables this feature.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by DandyDeveloper — DISMISSED** [review]

**Comment by DandyDeveloper** [comment]
LGTM, sorry for this taking so long. Merging when it passes.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by DandyDeveloper** [comment]
@imvalient Looks like the CI sees some problems. Possibly indentation? Can you triple check your work here?

**Comment by imvalient** [comment]
@DandyDeveloper thanks, it should be fixed now.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by imvalient** [comment]
@DandyDeveloper, I think that you have to approve the needed GitHub actions, right?

**Comment by DandyDeveloper** [comment]
@imvalient I actually think GH ACtions was having problems the other day... Going to do what I can to get these running.

**Review by DandyDeveloper — APPROVED** [review]

**Review by DandyDeveloper — APPROVED** [review]

**Comment by DandyDeveloper** [comment]
```Error: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field ObjectMeta.spec.template.metadata.annotations of type string
```

@imvalient Looks like its still broken. FYI: Do some local `helm template .` or `helm install` with and without the annotations. It should show the same as what we're seeing in the CI.

**Pull request closed without merging**
