### PR TITLE
[charts/redis-ha] Add a preStop script to trigger a failover before a redis master is terminated

### PR DESCRIPTION
**Pull request by adyxax**
#### What this PR does / why we need it:

I noticed that when a redis master gets terminated there is a downtime before a new one gets elected. This behavior can be fixed with a preStop script that checks if the terminating pod is a redis master and triggers a failover before shutting down if that is the case.

#### Special notes for your reviewer:

Do not hesitate to ask for clarifications or changes. I tried to respect the style of the surrounding code.

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by adyxax** [comment]
@DandyDeveloper : Please review this PR when you have time, thank you!

**Comment by DandyDeveloper** [comment]
@adyxax  Great idea. I like this.

I'll jump on the review later today. One immediate thing. This should be a minor increase. Not a patch increase.

**Comment by adyxax** [comment]
Thank you, I updated the version to a minor increase.

**Comment by adyxax** [comment]
@DandyDeveloper : if I can do anything to help with your review do not hesitate to ask.

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
