### PR TITLE
Add separate redis_readiness check

### PR DESCRIPTION
**Pull request by tahajahangir**
With recent changes to redis_liveness.sh, the POD (wrongly) will be marked as ready when a sync is in progress.
I've added an new redis_readiness.sh.

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@tahajahangir Can you bump the chart version? 

Just to be clear; 

 - Liveness will be OK during SYNC.
 - Readiness will only be OK when PONG comes back, confirming it is no longer syncing.

Correct?

**Comment by tahajahangir** [comment]
@DandyDeveloper Exactly correct.
I bumped the version on PR-113

**Comment by DandyDeveloper** [comment]
@tahajahangir Merged. Need another bump on this PR too please.

**Comment by DandyDeveloper** [comment]
Bumped and tested. Just waiting on CI.

**Pull request merged**
