### PR TITLE
[charts/redis-ha] feat: Add pdb for haproxy

### LINKED ISSUE #105: [chart/redis_ha][REQUEST] Add PodDisruptionBudget to HAProxy instances
**Is your feature request related to a problem? Please describe.**
Currently you can manage a PodDisruptionBudget for the redis statefulsets, but not for the HA Proxy deployment. As a result, even though the redis backend will be kept HA during a maintenance task, it is possible to cause the HA Proxy service to become temporarily unavailable.

**Describe the solution you'd like**
Add an additional PDB for the HA Proxy deployment. 

**Describe alternatives you've considered**
Currently manually managing the second PDB as part of CI/CD system but it is cleaner to have it all in Helm.

### PR DESCRIPTION
**Pull request by paranoidsp**
#### What this PR does / why we need it:
Adds a pdb for haproxy

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #105 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by DandyDeveloper — DISMISSED** [review]
@paranoidsp Sorry it took so long to get back to you on this.

Can you bump the chart version?

Worth noting, I have some other PRs coming in shortly.

**Comment by DandyDeveloper** [comment]
@paranoidsp You may need to pull in master as well. That should fix the tests.

**Comment by procslash** [comment]
I've bumped it from 4.12.15 to 4.12.16, would you like me to bump it to 4.13.0 instead?

**Comment by paranoidsp** [comment]
I've bumped it to 4.12.16 (from 4.12.15), would you like me to bump it to 4.13.0 instead?

**Comment by paranoidsp** [comment]
Ignore, bumped to .17 after checking master.

**Comment by DandyDeveloper** [comment]
Can you make it `.18`? I had to merge something else.

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
