### PR TITLE
[chart/redis-ha] Make exporter probes optional

### PR DESCRIPTION
**Pull request by sonrai-doyle**
#### What this PR does / why we need it:
This adds the option to remove the livenessProbe and readinessProbe from the exporter container. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@sonrai-doyle May be better here to do a `toYaml` templating for the probes that way if people want to remove it they just add the following to the values file:

```
livenessProbe: {}
```

**Comment by DandyDeveloper** [comment]
@sonrai-doyle Any way you can update / give input on my comment? Will close soon if I don't hear from you.,

**Comment by sonrai-doyle** [comment]
Sorry @DandyDeveloper missed your comment while I was away on vacation. Will look at making the suggested change as I can.

**Comment by mhkarimi1383** [comment]
+1 Waiting for this, sometimes Redis wants to recover, and we want exporter to be enabled (without probes) since it will get timeouts, etc. and makes entire pod to be unavailable.

**Comment by sonrai-doyle** [comment]
@DandyDeveloper Sorry for the delay in addressing your comments. Would you be able to re-review?

**Comment by mhkarimi1383** [comment]
But that would be better if we can make all of the probes optional

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
