### PR TITLE
[redis-ha] Terminate TLS on HAproxy

### PR DESCRIPTION
**Pull request by GGre4**
#### What this PR does / why we need it:
- Option to terminate TLS on Haproxy (volume mount certs & updated haproxy config )
- Option to use service account of own choice on haproxy
- Option to change container port on haproxy deployment
- Option to change service port on haproxy service 

#### Which issue this PR fixes
n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@GGre4 Oh you already reopened. Thank you. Jumping on this/.

**Review by DandyDeveloper — COMMENTED** [review]
Only thing I'd add to this is the potential breaking change in the README. 

As some people may be reliant on `redis.port` which has now changed.

**Comment by GGre4** [comment]
@DandyDeveloper I updated the readme, please let me know what you think?

**Comment by DandyDeveloper** [comment]
Made a small change, letting CI run now.

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
