### PR TITLE
[chart/redis-ha] issue-161: Resolve template issues with values.sentinel.auth

### LINKED ISSUE #161: [chart/redis-ha][BUG] Sentinel liveness check fails with Redis 6.2.6
**Describe the bug**
When using Redis 6.2.6 with `auth` enabled (but not `sentinel.auth`), the Sentinel liveness check always fails.

**To Reproduce**
```
helm install test dandydev/redis-ha --set auth=true --set redisPassword=password --set image.tag=6.2.6-alpine
```
The first of three pod is created and never becomes ready.

**Expected behavior**
Three pods should be created and become ready.

**Additional context**
Redis 6.2.5 work fine.

When running the liveness check by hand, the result is:
```
/data $ /health/sentinel_liveness.sh 
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

The issue is that authentication is enabled when pinging the Sentinel using the auth condition for Redis, rather than checking for `sentinel.auth`:
https://github.com/DandyDeveloper/charts/blob/c3c4e1c8bbe845bad3cc595781b32543cca10cc6/charts/redis-ha/templates/_configs.tpl#L619-L621

### PR DESCRIPTION
**Pull request by sonrai-doyle**
#### What this PR does / why we need it:
Resolves logic issues in the templating related to `Values.sentinel.auth`

#### Which issue this PR fixes
  - fixes #161

#### Special notes for your reviewer:
I have not tested these changes myself

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by DandyDeveloper — DISMISSED** [review]

**Comment by DandyDeveloper** [comment]
@sonrai-doyle Thank you for the contribution. Getting this merged in now.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by LongLiveCHIEF** [comment]
@DandyDeveloper should this have made the default image tag (and appVersion) to `6.2.6-alpine`? I notice it is still `6.2.5-alpine`, and #161 doesn't occur when using redis:6.2.5  images.

**Comment by DandyDeveloper** [comment]
@LongLiveCHIEF Worth noting this bug only occurs when auth is disabled and sentinel auth is enabled. 

I don't think the Redis image had any particular merit to this having impact. Unless I'm misunderstanding?

**Comment by sonrai-doyle** [comment]
Sorry, I may have misunderstood #161. As @DandyDeveloper stated, this does fix a particular use case, although it may not be the one outlined in the issue.

**Comment by LongLiveCHIEF** [comment]
Initially, i had the same issue as the _language_ @bootcc used in the original report, where 6.2.6 with auth enabled (but not sentinel auth) failed, but using tag 6.2.5 did not fail. The code he called out though doesn't appear to me to affect the language of the report, rather it affects a bug with sentinel auth configuration.

So in the #161 original report it was a bug being reported when redis auth was set but sentinel auth was not.

If I'm reading this correctly, this PR fixes a bug where sentinel auth is enabled but redis is not.

**Comment by sonrai-doyle** [comment]
I reviewed issue #161 and I think this PR would resolve both use-cases. 

(Unconfirmed by me) It appears that 6.2.6 would fail the liveness check for sentinel because the logic in the template was broken and it was attempting to use a sentinel password when it was disabled.  I assume 6.2.5 sentinel just ignored the faulty password because it wasn't expecting one and that 6.2.6 failed because it received a password and wasn't expecting one. 

I fixed the template logic and sentinel should now only receives a password if it's enabled. Someone should re-try 6.2.6 with only a redis password and I'd bet it would now work.

**Comment by DandyDeveloper** [comment]
I did not explicitly look at this use case because the code seemed solid but for the sake of thoroughness I'll try and test tomorrow

**Pull request merged**
