### PR TITLE
[stable/redis-ha] Remove not needed data echo and auth warning

### PR DESCRIPTION
**Pull request by lord-kyron**
#### What this PR does / why we need it:
This PR removes the unneeded date echo printing before it actually again print da date on the next command execution line. It also adds the '--no-auth-warning' option to all redis-cli commands, as it removes the unneeded warning outputs in the pods logs.

#### Which issue this PR fixes
n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. ``)

### CODE REVIEW

**Comment by lord-kyron** [comment]
@DandyDeveloper can you please review this PR? I am intending to use this chart in production and removing not needed messages from pod logs will be great! Thanks!

**Review by DandyDeveloper — APPROVED** [review]

**Comment by DandyDeveloper** [comment]
Looks good, before merge I need to check a couple things. I'll be online tonight to check.

**Comment by lord-kyron** [comment]
@DandyDeveloper thank you!

**Comment by lord-kyron** [comment]
@DandyDeveloper when do you plan to review and merge this? it will be nice to have it before we use this chart in production.
Also, there is another pull request, which is good to have before we hit Kubernetes 1.25 as then we will have a problem with the API version.
It is this one: https://github.com/DandyDeveloper/charts/pull/210
please, check it also!
Thank you!

**Pull request merged**
