### PR TITLE
[stable/redis-ha] Remove Values.persistentVolume.reclaimPolicy

### LINKED ISSUE #20: [chart/redis-ha][BUG] Can not set Values.persistentVolume.reclaimPolicy
**Describe the bug**

Setting Values.persistentVolume.reclaimPolicy for the redis-ha chart results in an error on `helm install`

**To Reproduce**

1. Create a new values.yaml file named `values-pv-reclaim-policy-bug.yaml`:

```yaml
persistentVolume:
  size: 2Gi
  reclaimPolicy: "Delete"
```

2. From the repo root dir, install the chart with Helm 3

```
helm install redis-ha-will-fail ./charts/redis-ha -f values-pv-reclaim-policy-bug.yaml
```

3. See error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.volumeClaimTemplates[0]): unknown field "persistentVolumeReclaimPolicy" in io.k8s.api.core.v1.PersistentVolumeClaim
```

**Expected behavior**

Setting Values.persistentVolume.reclaimPolicy should not result in an error on `helm install`

**Additional context**
```
helm version
>>> version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

```
kubectl version
>>> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:48Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
>>> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
minikube version
>>> minikube version: v1.9.2
>>> commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
```

### PR DESCRIPTION
**Pull request by daniel-cortez-stevenson**
#### What this PR does / why we need it:

The reclaimPolicy values configuration key was removed and the
corresponding value it sought to set in the redis-ha StatefulSet was
removed (along with the if statement surrounding it).

The [StatefulSet documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage
) indicates that when StatefulSets have
PersistentVolumeClaims, they must be deleted manually. So, it seems to me that trying to set the reclaim policy in this context is not going to work. 

#### Which issue this PR fixes

  - fixes #20

#### Special notes for your reviewer:

Is there another solution, which would support this functionality? Outside of testing purposes, when would someone want to set the policy as Delete? Is this functionality even worth supporting, in the case it only serves as a test env helper?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@daniel-cortez-stevenson That is news to me.... I thought the reclaim policy used to work... I guess things have either changed or this is just a mistake.

Thank you.

**Comment by DandyDeveloper** [comment]
@daniel-cortez-stevenson Can you sign your commits and do a force push please?

**Comment by daniel-cortez-stevenson** [comment]
> @daniel-cortez-stevenson Can you sign your commits and do a force push please?
> 
> Then I can merge this.

Done. If I messed up the signing again, let me know .. I'm new to the DCO.

Thanks for maintaining this chart - it's helpful 🤝

**Comment by daniel-cortez-stevenson** [comment]
> > @daniel-cortez-stevenson Can you sign your commits and do a force push please?
> > Then I can merge this.
> 
> Done. If I messed up the signing again, let me know .. I'm new to the DCO.
> 
> Thanks for maintaining this chart - it's helpful 🤝

@DandyDeveloper Oops - now the commits are signed - cheers!

**Comment by daniel-cortez-stevenson** [comment]
@DandyDeveloper Still feeling like this is the right move? Have I missed anything to prep the merge?  🍻

**Comment by DandyDeveloper** [comment]
> @DandyDeveloper Still feeling like this is the right move? Have I missed anything to prep the merge?  🍻 

Just need to test it. Having difficulties finding a good time. Will try and get to it tomorrow my morning (JST)

**Pull request merged**
