### PR TITLE
redis-ha: add custom command and args for sentinel container

### PR DESCRIPTION
**Pull request by bootc**
#### What this PR does / why we need it:
This allows overriding the command and arguments for the sentinel container.

#### Special notes for your reviewer:
I'm trying to run [Valkey](https://valkey.io/) with this chart, and the sentinel container needs a custom command/args to work correctly.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@bootc Looks great. Thank you! Can you pull in master and bump the patch again?

**Comment by bootc** [comment]
@DandyDeveloper I've rebased against current `master`.

**Comment by nico151999** [comment]
@DandyDeveloper sorry for pinging you after bootc did but is there a reason you have not come up with an approving review?

**Comment by DandyDeveloper** [comment]
@nico151999 Nope, just missed the emails.

**Pull request merged**
