### PR TITLE
[stable/redis-ha] Fixes issue #86

### LINKED ISSUE #86: [chart/redis-ha][REQUEST] - Extend redis.config and sentinel.config
**Is your feature request related to a problem? Please describe.**
Right now we cannot configure multiple configuration lines through redis.config. I know redis.customConfig can be used to solve this problem but it will be nice to have redis.config take care of this as well. Furtermore, sentinel.config values adds "sentinel {{key}} <master-group-name> {{value}}" for all values, it will be nice to support other config values which doesn't need to start with "sentinel" keyword in sentinel.conf file 

**Describe the solution you'd like**
We can have a key called "redis.config.multipleLineConfig" where multipleLineConfig is just a blob of data like:

```
redis:
  config:
    multipleLineConfig: |
        save 100 60
        save 200 30
```
In _configs.tpl we can check for this key to just copy this whole blob of data to redis.conf

For sentinel:
We can have "sentinel.config.otherConfig" where otherConfig can have values which doesn't need to be pre appended by "sentinel {{key}} ..."

**Describe alternatives you've considered**
Alternative is to use redis.customConfig and sentinel.customConfig

### PR DESCRIPTION
**Pull request by SarjakSShah**
#### What this PR does / why we need it:
Resolves issue #86 
#### Which issue this PR fixes
  - fixes #86 

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by SarjakSShah** [comment]
@DandyDeveloper : Please review this PR, thank you

**Comment by DandyDeveloper** [comment]
@SarjakSShah Im a little confused by this, the current configuration for the normal Redis already supports whatever options you want to place in it as it just iterates over the k/v passed into the `.Values.redis.config` and maps it out: 

https://github.com/DandyDeveloper/charts/blob/2c09a73f1fb61720c25c7b353c030c3de76703a2/charts%2Fredis-ha%2Ftemplates%2F_configs.tpl#L24

On the Sentinel side, can you give me an option that isn't supported? AFAIK all options in the sentinel.conf are all prefixed with `sentinel`.

**Comment by SarjakSShah** [comment]
> @SarjakSShah Im a little confused by this, the current configuration for the normal Redis already supports whatever options you want to place in it as it just iterates over the k/v passed into the `.Values.redis.config` and maps it out:
> 
> https://github.com/DandyDeveloper/charts/blob/2c09a73f1fb61720c25c7b353c030c3de76703a2/charts%2Fredis-ha%2Ftemplates%2F_configs.tpl#L24
> 
>>> This is to add configuration like 
```        
save 100 60
save 200 30
``
Currently you can only add one "save" configuration to `.Values.redis.config` 

> On the Sentinel side, can you give me an option that isn't supported? AFAIK all options in the sentinel.conf are all prefixed with `sentinel`.

>>> For sentinel you can add configuration options which does not start with keyword 'sentinel'. For example, we can add "always-show-logo yes" configuration to sentinel.conf. Furtermore, sentinel inherits all its networking configuration from redis configuration but we can override that by placing that networking configuration in sentinel.conf for sentinel. For example, we can add "tcp-backlog 512" as a configuration in sentinel.conf

I hope this explanation makes sense, if not let me know and I can elaborate

**Comment by DandyDeveloper** [comment]
@SarjakSShah Makes complete sense! I'm just wondering if there's a better way to do this, let me have a quick think. 

Maybe for these niche use cases it'd be better if we allow people to mount in their own configmap? My gut feeling is adding the option your suggesting might be more confusing to people and really only solve super niche scenarios (that I haven't come across before). 

But if we just allow individuals to define their own ConfigMap for specific components, then they can template the entire thing themselves through Helm / outside of helm. Without having an ugly config inside the values file. 

Thoughts?

**Comment by SarjakSShah** [comment]
> @SarjakSShah Makes complete sense! I'm just wondering if there's a better way to do this, let me have a quick think.
> 
> Maybe for these niche use cases it'd be better if we allow people to mount in their own configmap? My gut feeling is adding the option your suggesting might be more confusing to people and really only solve super niche scenarios (that I haven't come across before).
> 
> But if we just allow individuals to define their own ConfigMap for specific components, then they can template the entire thing themselves through Helm / outside of helm. Without having an ugly config inside the values file.
> 
> Thoughts?

inside `{{- define "config-redis.conf" }}` the else block seems really helpful as it uses the values we defined in values.yaml file and generates the redis.conf for us. If we do what you are suggesting then I am just worried that we have to define all the config parameters ourselves for redis.conf in that external template.

**Comment by SarjakSShah** [comment]
> > @SarjakSShah Makes complete sense! I'm just wondering if there's a better way to do this, let me have a quick think.
> > Maybe for these niche use cases it'd be better if we allow people to mount in their own configmap? My gut feeling is adding the option your suggesting might be more confusing to people and really only solve super niche scenarios (that I haven't come across before).
> > But if we just allow individuals to define their own ConfigMap for specific components, then they can template the entire thing themselves through Helm / outside of helm. Without having an ugly config inside the values file.
> > Thoughts?
> 
> inside `{{- define "config-redis.conf" }}` the else block seems really helpful as it uses the values we defined in values.yaml file and generates the redis.conf for us. If we do what you are suggesting then I am just worried that we have to define all the config parameters ourselves for redis.conf in that external template.

@DandyDeveloper thoughts?

**Comment by DandyDeveloper** [comment]
@SarjakSShah You can always reference that helper inside of the localized templated config, assuming you use redis-ha as a dependency for your chart. 

I do see the reason for this change... Give me some time to think, but I'd like you to try my suggestion in practice to see if it achieves the same as you'd expect without adding this.

**Comment by DandyDeveloper** [comment]
@SarjakSShah Did you have an opportunity to try my suggestion? 

I'm still on the fence about this. IT'd be nice to have a second opinion from other users, but I don't know how to get people involved as I'm technically the only active maintainer...

**Comment by SarjakSShah** [comment]
> @SarjakSShah Did you have an opportunity to try my suggestion?
> 
> I'm still on the fence about this. IT'd be nice to have a second opinion from other users, but I don't know how to get people involved as I'm technically the only active maintainer...

@DandyDeveloper I haven't yet tried it, but I will try it next week and update you

**Comment by SarjakSShah** [comment]
@DandyDeveloper Sorry I haven't had time to get to this

I guess I need more information as to what you are asking me to try out

This is my understanding:
(1) We would add a switch to the existing configmap so that we can disable it
(2) Then we add a configmap template ( in the umbrella chart ) - this template will pretty much define the redis.conf and sentinel.conf externally?

Is my understanding correct?

**Comment by DandyDeveloper** [comment]
@SarjakSShah I completely missed your reply, I'm sorry. 

Yes, that would be my suggestion. Because I feel like "appending" to an existing configmap is more dangerous and error prone over giving the users the option of:

a. Use the default the chart offers
b. Provide your own config file. 

If you feel very strongly about appending though, I'm not opposed. It'd be nice to have some other opinions on what would work best here.

**Comment by DandyDeveloper** [comment]
I'm closing this out for now as housekeeping. I know this topic is still pending, but lets discuss in a refreshed PR if we decide what to do next.

**Pull request closed without merging**
