### PR TITLE
[stable/redis-ha] Add option to disable commands in redis config

### PR DESCRIPTION
**Pull request by lord-kyron**
#### What this PR does / why we need it:
We need this PR as it seems when an attempt is made to enter the "rename-command" key more than once in the config, this is impossible as the key is marked as duplicated. But this blocks us from using rename-command to disable FLUSHALL and FLUSHDB commands at the same time.

#### Which issue this PR fixes
n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lord-kyron** [comment]
@DandyDeveloper please, take a look at this as our organization needs this feature otherwise we cannot use the rename-command in the config as it is being treated as duplicated key when mentioned multiple times.
Thanks!

**Comment by lord-kyron** [comment]
@DandyDeveloper ?

**Review by DandyDeveloper — APPROVED** [review]
Good change.

**Comment by DandyDeveloper** [comment]
@lord-kyron The only thing I might end up rolling back is the defaults. It's a good addition but its plausible existing users might be consuming these and for them to "suddenly" not work using this could be concerning. For now though, I think these are solid defaults. Merging.

**Pull request merged**
