### PR TITLE
[charts/redis-ha] Upgrade HAProxy to LTS version

### PR DESCRIPTION
**Pull request by 34fathombelow**
#### What this PR does / why we need it:
This PR bumps HAProxy image to an LTS version, [current version is EOL 2023-Q1](https://www.haproxy.org/).
I did not see any breaking changes from 2.5 --> 2.6, all tests passed on my end.

#### Special notes for your reviewer:
Thanks for all your hard work, have an awesome day!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by 34fathombelow** [comment]
@DandyDeveloper Can I please get a review?   Or have any thoughts on this?

**Comment by DandyDeveloper** [comment]
@34fathombelow on it!

**Review by DandyDeveloper — APPROVED** [review]
Looks good, I don't see any breaking changes. Lets get the ConfigMap tests running just incase.

**Comment by 34fathombelow** [comment]
@DandyDeveloper Did I miss something?  I have signed all my commits not sure why is says merging is blocked.

**Comment by DandyDeveloper** [comment]
Most likely my pull or master upset the conditions.

Don't worry, I'll get it merged soon.

**Pull request merged**
