### PR TITLE
[charts/redis-ha] Upgrade redis exporter to latest version

### PR DESCRIPTION
**Pull request by baurmatt**
#### What this PR does / why we need it:

Upgrade redis exporter to latest version

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [?] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@baurmatt Can you merge with master and up the Chart version? I just merged another change. Thank you!

**Comment by baurmatt** [comment]
@DandyDeveloper Fixed! :)

**Comment by DandyDeveloper** [comment]
@baurmatt Did you bump by 2 major versions?

We only need one... Or am I misreading?Github for mobile can be unreliable.

**Comment by baurmatt** [comment]
@DandyDeveloper No, you're absolutely right! I've fixed the typo... Good catch, thanks! :)

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
